---
title: "HW5"
author: "Bertrand Black"
date: "3 March 2021"
output: html_document
---

### Question 1 

a.
```
  x <- 1.1 
  a <- 2.2 
  b <- 3.3 
  
  z <- x^(a^b)
  print(z)
  
 [1] 3.61714
``` 
b. 
```
  z <- (x^a)^b
  z
  
  [1] 1.997611
```
c. 
```
  z <- (3*(x^3))+(2*(x^2))+1
  z 
  
  [1] 7.413
```

### Question 2 

a. 
```
  a <-c(seq(1,8),seq(7,1))
  a

  [1] 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1
```
b. 
```
  b <-1:5
  vectorB <-rep(x=b,times=b)
  vectorB

  [1] 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5
```
c. 
```
  c <- 5:1
  vectorC <-rep(x=c, times=b)
  vectorC

  [1] 5 4 4 3 3 3 2 2 2 2 1 1 1 1 1
```

### Question 3


##### I. Create a vector of two random uniform numbers
```
  unitwo <- runif(2)
  unitwo

  [1] 0.1463978 0.6740155
```

##### II. Convert to from Cartesian coordinates`(x,y)` to polar coordinates: `(r, theta)` 

i. Calculate radius or magnitude `r`  
```
  r <- ((unitwo[1]^2)+(unitwo[2]^2))^0.5
  r

  [1] 0.6897312
```

ii. Calculate the angle or direction `theta` and convert to from radian to degrees
```
  intan <- atan(unitwo[2]/unitwo[1])
  intan    

  [1] 1.356916

  theta <- (intan)*(180/pi)
  theta

  [1] 77.74556
```

III. Combine into a single polar coordinate vector
```
  pcoor <- c(r,theta)
  pcoor

  [1]  0.6897312 77.7455586 = (r,theta)
```
### Question 4

##### Create the queue
```
  queue <-c("sheep","fox","owl","ant")
  queue

  [1] "sheep" "fox"   "owl"   "ant"  
```

##### a. Add the serpent to the queue
```
  queue <-c(queue,"serpent")
  queue

  [1] "sheep"   "fox"     "owl"     "ant"        "serpent"
```
##### b. Remove the sheep from the queue
```
  queue = queue[-1]
  queue
  [1] "fox"     "owl"     "ant"     "serpent"
```
##### c. Put the donkey at the front of the line
```
  queue <-c("donkey",queue)
  queue

  [1] "donkey"  "owl"     "ant"     "serpent"
```
##### d. Take the serpent out of the line
```
  queue = queue[-5]
  queue

  [1] "donkey" "fox"    "owl"    "ant"   
```
##### e. Take the owl out of the line
```
  queue = queue[-3]
  queue

  [1] "donkey" "fox"    "ant"   
```
##### f. Insert the aphid after the fox and before the ant 
```
  queue <-append(queue, "aphid", after = 2)
  queue

  [1] "donkey" "fox"    "aphid"  "ant"
```
##### g. Deterimine the position of the ant
```
  which(queue == "aphid")

  [1] 3
```
### Question 5
#### a. Create list from 1 to 100 
```
  list <-1:100
  list

  [1]   1   2   3   4   5   6   7   8   9  10 11  12  13
 [14]  14  15  16  17  18  19  20  21  22  23  24  25  26
 [27]  27  28  29  30  31  32  33  34  35  36  37  38  39
 [40]  40  41  42  43  44  45  46  47  48  49  50  51  52
 [53]  53  54  55  56  57  58  59  60  61  62  63  64  65
 [66]  66  67  68  69  70  71  72  73  74  75  76  77  78
 [79]  79  80  81  82  83  84  85  86  87  88  89  90  91
 [92]  92  93  94  95  96  97  98  99 100
 ```
#### b. Create a subset of the vector where the numbers are not divisible by 2
 ```
list <- list[which(list%%2 != 0)]
list

 [1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35
  [19] 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71
  [37] 73 75 77 79 81 83 85 87 89 91 93 95 97 99
```
#### c. Create a subset of the vector where the numbers are not divisible by 3
 ```
  list <- list[which(list%%3 != 0)]
  list

  [1]  1  5  7 11 13 17 19 23 25 29 31 35 37 41 43 47 49 53
  [19] 55 59 61 65 67 71 73 77 79 83 85 89 91 95 97
```
#### d. Create a subset of the vector where the numbers are not divisible by 7
```
  list <- list[which(list%%7 != 0)]
  list
```
#### e. Print out of final list from 1 to 100 with integers not divisible by 2,3, or 7. 
```
  print(list)
  [1]  1  5 11 13 17 19 23 25 29 31 37 41 43 47 53 55 59 61
  [19] 65 67 71 73 79 83 85 89 95 97
```

