---
title: "HW6"
author: "Bertrand Black"
date: " 10 March 2021"
output: html_document
---

### Question 1 
#### Assign to the variable `n_dims` a single random interger between 3 and 10
```
n_dims <-as.integer(runif(1,2,10))
n_dims

[1] 5
```

#### Create a vector of consecutive intergers from 1 to `n_dims^2`
```
vector <-1:n_dims^2
vector

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21
[22] 22 23 24 25
```

#### Use the sample function to randomly shuffle these values 
```
vector_s <-sample(vector)
vector_s

[1] 14 19  6 21 18  4 17  1 23  5  9  7 15  2 20  3 22 12
[19] 11 24  8 10 13 16 25
```
#### Create a square matrix with these elements 
```
matrix <-matrix(data = vector_s, nrow= 5, ncol=5)
matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]   14    4    9    3    8
[2,]   19   17    7   22   10
[3,]    6    1   15   12   13
[4,]   21   23    2   11   16
[5,]   18    5   20   24   25
```
#### Print out the matrix 
```
print(matrix)

     [,1] [,2] [,3] [,4] [,5]
[1,]   14    4    9    3    8
[2,]   19   17    7   22   10
[3,]    6    1   15   12   13
[4,]   21   23    2   11   16
[5,]   18    5   20   24   25
```
#### Transpose the matrix rows and columns
```
t_matrix <-t(matrix)
print(t_matrix)

     [,1] [,2] [,3] [,4] [,5]
[1,]   14   19    6   21   18
[2,]    4   17    1   23    5
[3,]    9    7   15    2   20
[4,]    3   22   12   11   24
[5,]    8   10   13   16   25
```
#### Reprint the trasposed matrix. How has it changed? 
```
# it has switched the columns and the rows but the middle diagonal stays the same. 

print(t_matrix)

     [,1] [,2] [,3] [,4] [,5]
[1,]   14   19    6   21   18
[2,]    4   17    1   23    5
[3,]    9    7   15    2   20
[4,]    3   22   12   11   24
[5,]    8   10   13   16   25
```
#### Calculate the sum and the meanof the elements in the first and the last row
```
mean(t_matrix[1,])

[1] 15.6

mean(t_matrix[5,])

[1] 14.4
```
#### Apply the eigen function to your matrix 
```
eigen(t_matrix)

eigen() decomposition
$values
[1]  64.761662  14.393273 -10.101620   8.040156   4.906529

$vectors
          [,1]        [,2]        [,3]       [,4]
[1,] 0.5378774  0.54464826  0.05750911 -0.7410977
[2,] 0.3308764  0.60376214  0.55258764 -0.4056055
[3,] 0.3632573 -0.37783908 -0.33930463 -0.1007367
[4,] 0.4692722 -0.05110515 -0.70664897  0.1842992
[5,] 0.4990356 -0.43983570  0.27723492  0.4920816
           [,5]
[1,] -0.4748318
[2,] -0.3162274
[3,] -0.5535186
[4,]  0.1448281
[5,]  0.5892173
```
#### What kind of numbers are `$values` and `$vectors`?
```
str(eigen(t_matrix)$values)

# num [1:5] 64.76 14.39 -10.1 8.04 4.91 

str(eigen(t_matrix)$vectors)

# num [1:5, 1:5] 0.538 0.331 0.363 0.469 0.499

# These are double precision numeric values or real numbers. All the elements in this vector are equal to zero and are identical to a numeric vector. 
```
#### Use the `typeof()` function to figure out there type. 
```
typeof(eigen(t_matrix)$vector)
[1] "double"

typeof(eigen(t_matrix)$values)
[1] "double"
```
#### Rerun code and generate a matrix of different size from the random number set assinged to `n_dims`
```
n_dims <-as.integer(runif(1,2,10))
n_dims

[1] 8

vector <-1:n_dims^2
vector

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
[19] 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
[37] 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
[55] 55 56 57 58 59 60 61 62 63 64

# Yes the code worked when I reran it and the matrix changed size as the new number was 8. 

```
### Question 2
#### Create a list with the following named elements: 
* `my_matrix` (4x4 matrix with random uniform values)
* `my_logical` (100 element vector of true or false values)
* `my_letters` (26 element vector of all the lower case letters in random order)
```
the_list <-list(my_matrix = matrix (runif(16), nrow =4), my_logical = runif(100) > 0.1, my_letters = sample(letters[1:26],26))

the_list[["my_matrix"]]
          [,1]      [,2]       [,3]       [,4]
[1,] 0.9556791 0.3524507 0.75540468 0.33186059
[2,] 0.3825749 0.2366716 0.09588194 0.02724992
[3,] 0.8137224 0.1522032 0.44575420 0.49798174
[4,] 0.1105275 0.8311172 0.02067214 0.35851123

the_list[["my_logical"]]
  [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [10]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
 [19]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
 [28]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [46]  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
 [55]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [64]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [82]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
 [91]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE
[100]  TRUE

the_list[["my_letters"]]
 [1] "q" "f" "r" "o" "k" "y" "t" "h" "z" "i" "u" "x" "j" "n"
[15] "p" "c" "g" "d" "a" "l" "v" "m" "e" "b" "w" "s"
```
#### Create a new list with element [2,2] from the matrix, the second element of the logical and letter vectors. 
```
new_list <-list(the_list$my_matrix[2,2], the_list$my_logical[2], the_list$my_letters[2])
new_list
[[1]]
[1] 0.2366716

[[2]]
[1] TRUE

[[3]]
[1] "f"
```
#### Use the `typeof` function to confirm the underlying data types of each component in the new list. 
```
typeof(new_list[[1]])
[1] "double"

typeof(new_list[[2]])
1] "logical"

typeof(new_list[[3]])
[1] "character"
```

#### Combined all the elements from the new list into a single vector 
```
comb_list <-c(new_list[[1]],new_list[[2]],new_list[[3]])
comb_list
[1] "0.236671602120623" "TRUE"             
[3] "f" 
```
#### What is the data type of this combined vector
```
typeof(comb_list)
[1] "character"
```
### Question 3
#### Create a data frame with two variables (=columns) and 26 cases (=rows). 

#### Call the first variable `my_unis`, and fill with 26 random uniform values from 0 to 10
```
my_unis <- runif(26,0,10)
my_unis
 [1] 1.96454276 1.23066866 5.22666241 5.63249468 5.75754176
 [6] 2.97826058 2.36842047 0.95890153 9.98134558 9.54225294
[11] 2.75255304 8.46748048 3.43260886 8.91715827 6.09827726
[16] 3.26926274 6.31458160 5.41024824 3.16415130 7.20737471
[21] 8.52239053 7.78738053 8.21678683 0.68563047 2.60816600
[26] 0.01539938
```
#### Create a second variable called `my_letters` and fill with 26 capital letters in random order. 
```
my_letters <-sample(LETTERS)
my_letters

[1] "S" "W" "T" "B" "V" "P" "M" "D" "I" "K" "U" "Q" "Y" "X"
[15] "A" "N" "H" "O" "L" "Z" "J" "R" "G" "F" "C" "E"
```
#### Merge variables into a data frame 
```
df

     my_unis my_letters
1  7.02755088          S
2  3.42911551          W
3  1.99167482          T
4  4.89820920          B
5  1.29260868          V
6  8.09304784          P
7  8.85394181          M
8  0.09398782          D
9  3.01766852          I
10 6.73913608          K
11 9.29692571          U
12 1.73781512          Q
13 7.04142915          Y
14 9.71044533          X
15 4.34816799          A
16 9.24221391          N
17 0.41918140          H
18 4.56203089          O
19 3.63091270          L
20 3.48183388          Z
21 0.43883703          J
22 4.27534597          R
23 5.71662225          G
24 4.61888542          F
25 2.26485624          C
26 6.04334230          E
```

#### Use a single line of code in the `my_unis` variable to select 4 random rows and replace the numerical values with the `NA`. 
```
df[sample(nrow(df),4), 'my_unis'] <-NA
df
      my_unis my_letters
1  7.02755088          S
2          NA          W
3  1.99167482          T
4  4.89820920          B
5  1.29260868          V
6          NA          P
7  8.85394181          M
8  0.09398782          D
9  3.01766852          I
10 6.73913608          K
11 9.29692571          U
12         NA          Q
13 7.04142915          Y
14 9.71044533          X
15 4.34816799          A
16 9.24221391          N
17 0.41918140          H
18 4.56203089          O
19 3.63091270          L
20 3.48183388          Z
21 0.43883703          J
22 4.27534597          R
23         NA          G
24 4.61888542          F
25 2.26485624          C
26 6.04334230          E
```

#### Write a single line of code for `my_unis` to identify the rows with missing values
```
which(is.na(df[,1]) == TRUE)
1]  2  6 12 23

# Rows 2, 6, 12, and 23
```
#### Sort the second variable alphabetically 
```
df$my_letters <-sort(df$my_letters)
df
      my_unis my_letters
1  7.02755088          A
2          NA          B
3  1.99167482          C
4  4.89820920          D
5  1.29260868          E
6          NA          F
7  8.85394181          G
8  0.09398782          H
9  3.01766852          I
10 6.73913608          J
11 9.29692571          K
12         NA          L
13 7.04142915          M
14 9.71044533          N
15 4.34816799          O
16 9.24221391          P
17 0.41918140          Q
18 4.56203089          R
19 3.63091270          S
20 3.48183388          T
21 0.43883703          U
22 4.27534597          V
23         NA          W
24 4.61888542          X
25 2.26485624          Y
26 6.04334230          Z
```
#### Calculate the mean for the first variable; `my_unis`
```
mean(df$my_unis, na.rm=TRUE)
[1] 4.694963
```
